variable "s3_bucket_name" {}
variable "s3_bucket_Environment" {}
variable "bucket_iam_policy" {}
variable "index_document_html_file_path" {}
variable "error_document_html_file_path" {}
variable "routing_rules_json_array" {}
variable "allowed_methods" {}
variable "allowed_origins" {}
variable "allowed_headers" {}
variable "expose_headers" {}
variable "max_age_seconds" {}
variable "versioning_enabled" {}
variable "mfa_delete" {}
variable "s3_bucket_id" {}
variable "a_key_prefix_for_log_objects" {}
variable "lifecycle_rule_enabled" {}
variable "lifecycle_rule_unique_id" {}
variable "lifecycle_rule_name" {}
variable "lifecycle_rule_value" {}
variable "transition_1_storage_class" {}
variable "transition_1_date" {}
variable "transition_1_days" {}
variable "transition_2_storage_class" {}
variable "transition_2_date" {}
variable "transition_2_days" {}
variable "expiration_date" {}
variable "expiration_days" {}
variable "expired_object_delete_marker" {}
variable "noncurrent_version_transition_1_storage_class" {}
variable "noncurrent_version_transition_1_days" {}
variable "noncurrent_version_transition_2_storage_class" {}
variable "noncurrent_version_transition_2_days" {}
variable "noncurrent_version_expiration_days" {}
variable "role_arn" {}
variable "rule_satus_enabled" {}
variable "rule_unique_id" {}
variable "rule_priority" {}
variable "s3_bucket_arn" {}
variable "destination_storage_class" {}
variable "replica_kms_key_arn" {}
variable "access_control_translation_owner" {}
variable "account_id" {}
variable "sse_kms_encrypted_objects_enabled" {}
variable "rule_object_keyname_prefix" {}
variable "rule_tag_name" {}
variable "rule_tag_value" {}
variable "sse_algorithm" {}
variable "kms_master_key_id_arn" {}
