variable "image_id" {}
variable "instance_type_size" {}
variable "aws_launch_configuration_name" {}
variable "iam_instance_profile" {}
variable "key_name" {}
variable "security_groups_id" {}
variable "associate_public_ip_address" {}
variable "user_data" {}
variable "enable_monitoring" {}
variable "root_block_device_volume_size" {}
variable "root_block_device_volume_type" {}
variable "root_block_device" {}
variable "root_block_device_delete_on_termination" {}
variable "ebs_block_device_device_name" {}
variable "ebs_block_device_snapshot_id" {}
variable "ebs_block_device_volume_size" {}
variable "ebs_block_device_volume_type" {}
variable "ebs_block_device_iops" {}
variable "ebs_block_device_delete_on_termination" {}
variable "ebs_block_device_encrypted" {}
variable "ephemeral_block_device_device_name" {}
variable "ephemeral_block_device_Instance_Store_Device_Name" {}
variable "spot_price" {}
variable "placement_tenancy" {}