variable "s3_bucket_id" {}
variable "topic_events" {}
variable "sns_topic_arn" {}
variable "topic_unique_id_name" {}
variable "topic_object_key_name_prefix" {}
variable "topic_object_key_name_suffix" {}
variable "queue_events" {}
variable "sqs_topic_arn" {}
variable "queue_id" {}
variable "queue_object_key_name_prefix" {}
variable "queue_object_key_name_suffix" {}
variable "lambda_function_events" {}
variable "lambda_function_arn" {}
variable "lambda_function_id" {}
variable "lambda_function_object_key_name_prefix" {}
variable "lambda_function_object_key_name_suffix" {}