variable "aws_launch_template_name" {}
variable "aws_launch_template_description" {}
variable "block_device_mappings_device_name" {}
variable "block_device_mappings_no_device" {}
variable "block_device_mappings_virtual_name" {}
variable "ebs_delete_on_termination" {}
variable "ebs_encrypted" {}
variable "ebs_iops" {}
variable "kms_key_id" {}
variable "ebs_snapshot_id" {}
variable "ebs_volume_size" {}
variable "ebs_volume_type" {}
variable "capacity_reservation_preference" {}
variable "capacity_reservation_id" {}
variable "cpu_credits" {}
variable "disable_api_termination" {}
variable "ebs_optimized" {}
variable "elastic_gpu_specifications_type" {}
variable "elastic_inference_accelerator_type" {}
variable "iam_instance_profile_arn" {}
variable "iam_instance_profile_name" {}
variable "ami_to_launch" {}
variable "instance_initiated_shutdown_behavior" {}
variable "instance_market_options_market_type" {}
variable "spot_options_block_duration_minutes" {}
variable "spot_options_instance_interruption_behavior" {}
variable "spot_options_max_price" {}
variable "spot_instance_type" {}
variable "spot_options_valid_until" {}
variable "instance_type" {}
variable "kernel_id" {}
variable "key_name" {}
variable "license_configuration_arn" {}
variable "monitoring_enabled" {}
variable "associate_public_ip_address" {}
variable "delete_on_termination" {}
variable "network_interfaces_description" {}
variable "network_interfaces_device_index" {}
variable "ipv4_addresses" {}
variable "ipv4_address_count" {}
variable "network_interface_id" {}
variable "private_ip_address" {}
variable "ipv6_addresses" {}
variable "ipv6_address_count" {}
variable "security_groups" {}
variable "subnet_id" {}
variable "placement_instance_affinity" {}
variable "placement_instance_availability_zone" {}
variable "instance_placement_group_name" {}
variable "instance_host_id" {}
variable "spread_domain" {}
variable "tenancy" {}
variable "tag_specifications_resource_type" {}
variable "resource_tag_specifications_name" {}
variable "ram_disk_id" {}
variable "security_group_names" {}
variable "aws_launch_template_tag_name" {}
variable "user_data" {}