variable "_spot_instance_ami" {}
variable "spot_instance_type" {}
variable "spot_price" {}
variable "wait_for_fulfillment" {}
variable "spot_type" {}
variable "launch_group_for_spot_instance" {}
variable "block_duration_minutes" {}
variable "instance_interruption_behaviour" {}
variable "request_start_date_time" {}
variable "request_end_date_time" {}
variable "aws_spot_instance_request_tag_name" {}